"""
RockTranslate — High-Performance Synchronous Dual-Pane Workspace Viewer
Path: src/rocktranslate/ui_pyqt/widget/workspace_viewer.py

This module hosts the dual-pane Chromium engine (QWebEngineView).
It renders:
- Left pane: The original vector PDF using Mozilla's offline PDF.js viewer.
- Right pane: The dynamic translated HTML document parsed by HTMLTransformer.

Both frames communicate over a secure local channel. A background script 
implements real-time bidirectional scrolling synchronization, interactive 
splitter resizing, and adaptive grid columns.

Author: RockTranslate Contributors
License: MIT License
Version: 1.0.0
"""

import os
import json
import tempfile
import shutil
from typing import Optional, Dict, Any
from PyQt6.QtWebEngineWidgets import QWebEngineView
from PyQt6.QtWebEngineCore import QWebEngineSettings, QWebEnginePage
from PyQt6.QtCore import QUrl
from PyQt6.QtWidgets import QWidget


class SilentWebEnginePage(QWebEnginePage):
    """
    Custom WebEnginePage that silently filters out verbose console warnings 
    generated by PDF.js internal scroll mechanics.
    """

    def javaScriptConsoleMessage(
        self, 
        level: int, 
        message: str, 
        lineNumber: int, 
        sourceId: str
    ) -> None:
        # Silently discard editor and scroll alerts to avoid Python CLI clutter
        if "editor_alt_text" in message or "scrollPageIntoView" in message:
            return
        # --- PRINT ALL CONSOLE LOGS DIRECTLY TO PYTHON TERMINAL ---
        # print(f"🌐 [JS Console] {message}")
        # --------------------------------------------------------
        super().javaScriptConsoleMessage(level, message, lineNumber, sourceId)


class WorkspaceViewer(QWebEngineView):
    """
    Unified dual-pane rendering browser viewport implementing synchronous 
    scrolling coordinates and sliding transitions.
    """

    def __init__(self, parent: Optional[QWidget] = None) -> None:
        """
        Initializes the browser settings, rendering policies, and temporary workspaces.

        Args:
            parent: Optional parent QWidget.
        """
        super().__init__(parent)
        self._temp_dir: str = tempfile.mkdtemp()
        self._temp_workspace_path: Optional[str] = None
        self._zoom_factor: float = 1.0

        # Bind the custom silent page to bypass verbose console alerts
        self.setPage(SilentWebEnginePage(self))
        
        # Enforce strict local permissions to authorize communication between adjacent local iframes
        settings = self.settings()
        settings.setAttribute(QWebEngineSettings.WebAttribute.LocalContentCanAccessFileUrls, True)
        settings.setAttribute(QWebEngineSettings.WebAttribute.LocalContentCanAccessRemoteUrls, True)
        settings.setAttribute(QWebEngineSettings.WebAttribute.AllowRunningInsecureContent, True)

    def load_document(self, pdf_path: str, instrumented_html_path: str, pdfjs_dir_path: str) -> None:
        """
        Generates the master layout workspace HTML and loads it into the Chromium engine.

        Args:
            pdf_path: Path to the original PDF file.
            instrumented_html_path: Path to the translated workspace HTML file.
            pdfjs_dir_path: Path containing PDF.js web distribution.
        """
        self.cleanup_temp_files()

        # Sanitize paths for reliable Chromium filesystem resolution
        pdfjs_viewer: str = os.path.abspath(os.path.join(pdfjs_dir_path, "web/viewer.html")).replace("\\", "/")
        safe_pdf: str = os.path.abspath(pdf_path).replace("\\", "/")
        safe_html: str = os.path.abspath(instrumented_html_path).replace("\\", "/")

        # Append pagemode=none to hide PDF.js sidebar panel default displays
        left_iframe_src: str = f"file:///{pdfjs_viewer}?file=file:///{safe_pdf}#pagemode=none"
        right_iframe_src: str = f"file:///{safe_html}"

        # Master synchronous dual-pane template HTML
        master_html: str = f"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body, html {{
            margin: 0; padding: 0; width: 100%; height: 100%;
            overflow: hidden; font-family: 'Segoe UI', sans-serif;
            background: #1e202c;
            user-select: none;
        }}
        #workspace {{
            display: grid;
            grid-template-columns: 50% 6px 1fr;
            width: 100%;
            height: 100%;
            position: relative;
        }}
        .pane {{
            height: 100%; overflow: hidden; position: relative;
        }}
        #splitter {{
            width: 8px; height: 100%; background: #fafafc; cursor: col-resize;
            border: 1px; border-radius: 4px; border-color: #15151a; border-style: solid;
            position: relative; z-index: 100; transition: background 0.15s;
        }}
        #splitter:hover, #splitter.active {{
            background: #4f8ef7;
        }}
        iframe {{
            width: 100%; height: 100%; border: none;
        }}
        #workspace.dragging iframe {{
            pointer-events: none !important;
        }}
    </style>
</head>
<body>
    <div id="workspace">
        <div id="left-pane" class="pane">
            <iframe id="pdf-iframe" src="{left_iframe_src}"></iframe>
        </div>
        
        <div id="splitter"></div>
        
        <div id="right-pane" class="pane">
            <iframe id="html-iframe" src="{right_iframe_src}"></iframe>
        </div>
    </div>

    <script>
        var leftIframe = document.getElementById('pdf-iframe');
        var rightIframe = document.getElementById('html-iframe');
        var isSyncing = false;
        var lastSyncedPage = 0;
        var isPDFLoaded = false;

        // ── 1. LOGIQUE DU SPLITTER INTERNE (SÉPARATEUR) ──
        var splitter = document.getElementById('splitter');
        var workspace = document.getElementById('workspace');
        var isDragging = false;

        splitter.addEventListener('mousedown', function(e) {{
            isDragging = true;
            workspace.classList.add('dragging');
            splitter.classList.add('active');
            document.body.style.cursor = 'col-resize';
        }});

        document.addEventListener('mousemove', function(e) {{
            if (!isDragging) return;
            var containerWidth = workspace.clientWidth;
            var percentage = (e.clientX / containerWidth) * 100;
            
            if (percentage > 15 && percentage < 85) {{
                workspace.style.gridTemplateColumns = percentage + '% 6px 1fr';
            }}
        }});

        document.addEventListener('mouseup', function() {{
            if (isDragging) {{
                isDragging = false;
                workspace.classList.remove('dragging');
                splitter.classList.remove('active');
                document.body.style.cursor = 'default';
            }}
        }});

        // ── 2. CORRECTIF DISPOSITION EXCLUSIVE : MASQUAGE PROPRE DES COLONNES ET RE-AJUSTEMENT GRID 1FR ──
        function setPaneLayout(layout) {{
            var leftPane = document.getElementById('left-pane');
            var rightPane = document.getElementById('right-pane');
            var splitter = document.getElementById('splitter');
            var workspace = document.getElementById('workspace');
            
            if (layout === 'both') {{
                leftPane.style.display = 'block';
                rightPane.style.display = 'block';
                splitter.style.display = 'block';
                workspace.style.gridTemplateColumns = '50% 6px 1fr';
            }} else if (layout === 'pdf_only') {{
                leftPane.style.display = 'block';
                rightPane.style.display = 'none';
                splitter.style.display = 'none';
                workspace.style.gridTemplateColumns = '1fr';
            }} else if (layout === 'trans_only') {{
                leftPane.style.display = 'none';
                rightPane.style.display = 'block';
                splitter.style.display = 'none';
                workspace.style.gridTemplateColumns = '1fr';
            }}
        }}

        // ── 3. SYNCHRONISATION : GAUCHE (PDF) VERS DROITE (HTML) ──
        function syncPDFToHTML(pageIndex) {{
            if (isSyncing || !isPDFLoaded) return;
            isSyncing = true;
            
            try {{
                var rightDoc = rightIframe.contentWindow;
                var pageHex = (pageIndex + 1).toString(16);
                var targetPage = rightDoc.document.getElementById('pf' + pageHex);
                
                if (!targetPage) {{
                    var pages = rightDoc.document.querySelectorAll('.pf');
                    if (pages[pageIndex]) {{
                        targetPage = pages[pageIndex];
                    }}
                }}
                
                if (targetPage) {{
                    targetPage.scrollIntoView({{ behavior: 'smooth', block: 'start' }});
                }}
            }} catch(e) {{
                console.error("Erreur synchro Gauche->Droite :", e);
            }}
            
            setTimeout(function() {{ isSyncing = false; }}, 450);
        }}

        leftIframe.onload = function() {{
            var iframeWin = leftIframe.contentWindow;
            
            var checkInterval = setInterval(function() {{
                try {{
                    if (iframeWin.PDFViewerApplication && iframeWin.PDFViewerApplication.eventBus) {{
                        if (iframeWin.PDFViewerApplication.pdfDocument) {{
                            clearInterval(checkInterval);
                            isPDFLoaded = true;
                            iframeWin.PDFViewerApplication.pdfViewer.currentScaleValue = "50%";
                        }}

                        iframeWin.PDFViewerApplication.eventBus.on('documentloaded', function() {{
                            clearInterval(checkInterval);
                            isPDFLoaded = true;
                        }});

                        iframeWin.PDFViewerApplication.eventBus.on('pagechanging', function(evt) {{
                            var pageIndex = evt.pageNumber - 1; // 0-based
                            if (pageIndex !== lastSyncedPage && !isSyncing && isPDFLoaded) {{
                                lastSyncedPage = pageIndex;
                                syncPDFToHTML(pageIndex);
                            }}
                        }});
                    }}
                }} catch(e) {{}}
            }}, 100);
        }};

        // ── 4. CORRECTIF SYNCHRONISATION : ÉCOUTE DU SCROLL SUR LE CONTAINER NATION-SCALE DE pdf2htmlEX ──
        rightIframe.onload = function() {{
            var rightDocWindow = rightIframe.contentWindow;
            
            // C'est l'élément #page-container de pdf2htmlEX qui scrolle réellement, pas rightDocWindow !
            var scrollContainer = rightDocWindow.document.getElementById('page-container') || rightDocWindow;
            
            scrollContainer.addEventListener('scroll', function() {{
                if (isSyncing || !isPDFLoaded) return;
                
                var pages = rightDocWindow.document.querySelectorAll('.pf');
                var maxVisible = 0;
                var currentIdx = 0;
                var paneHeight = rightIframe.clientHeight; // Hauteur visible du conteneur parent

                pages.forEach(function(page, index) {{
                    var rect = page.getBoundingClientRect();
                    // Intersection mathématique géométrique dans le viewport de l'iframe
                    var visibleHeight = Math.max(0, Math.min(rect.bottom, paneHeight) - Math.max(rect.top, 0));
                    
                    if (visibleHeight > maxVisible) {{
                        maxVisible = visibleHeight;
                        currentIdx = index;
                    }}
                }});

                if (currentIdx !== lastSyncedPage) {{
                    lastSyncedPage = currentIdx;
                    isSyncing = true;
                    
                    try {{
                        var leftWin = leftIframe.contentWindow;
                        // SÉCURITÉ : On vérifie que PDF.js est prêt et a déjà instancié ses pages
                        if (leftWin.PDFViewerApplication && 
                            leftWin.PDFViewerApplication.pdfViewer && 
                            leftWin.PDFViewerApplication.pdfViewer.pagesCount > 0) {{
                            
                            leftWin.PDFViewerApplication.page = Number(currentIdx) + 1;
                        }}
                    }} catch(e) {{}}
                    
                    setTimeout(function() {{ isSyncing = false; }}, 450);
                }}
            }});
        }};
    </script>
</body>
</html>"""

        # Write workspace template to a secure temporary filesystem location
        with tempfile.NamedTemporaryFile(
            suffix=".html", delete=False, mode="w", encoding="utf-8", dir=self._temp_dir
        ) as f:
            f.write(master_html)
            self._temp_workspace_path = f.name

        self.load(QUrl.fromLocalFile(self._temp_workspace_path))

    def stream_translation(self, trans_id: str, translated_text: str) -> None:
        """
        Injects a single translated text node asynchronously into the HTML rendering iframe.

        Args:
            trans_id: Dynamic CSS/HTML routing tag of the element to update.
            translated_text: Translated string values to inject.
        """
        self._run_js_in_right_iframe({
            "action": "applyTranslation",
            "transId": trans_id,
            "translatedText": translated_text,
        })
    
    def prepare_page(self, page_idx: int) -> None:
        """
        Removes loading overlays (glass-morphic screens) and enables skeletal loaders 
        on a specific document page index.

        Args:
            page_idx: Page sequence number.
        """
        self._run_js_in_right_iframe({
            "action": "preparePage",
            "pageIdx": page_idx
        })

    def reset_page_to_waiting(self, page_idx: int) -> None:
        """
        Surgically resets a single page back to its waiting state,
        re-creating its glass overlay and clearing active shimmer skeletons.

        Args:
            page_idx: Page index to reset.
        """
        self._run_js_in_right_iframe({
            "action": "resetPage",
            "pageIdx": page_idx
        })

    def _run_js_in_right_iframe(self, js_code_as_msg_dict: Dict[str, Any]) -> None:
        """
        Sends structured JSON messages to the right iframe inside WebEngine pages securely.

        Args:
            js_code_as_msg_dict: The message dictionary containing action targets.
        """
        msg_json: str = json.dumps(js_code_as_msg_dict)
        self.page().runJavaScript(f"""
            (function() {{
                var iframe = document.getElementById('html-iframe');
                if (iframe && iframe.contentWindow) {{
                    iframe.contentWindow.postMessage({msg_json}, '*');
                }}
            }})();
        """)

    def clean_up_all_skeletons(self) -> None:
        """ Removes remaining loading skeletons once translation completes. """
        js: str = """
        var iframe = document.getElementById('html-iframe');
        if (iframe && iframe.contentWindow) {
            iframe.contentWindow.document.querySelectorAll('.shimmer-line').forEach(function(el) {
                el.classList.remove('shimmer-line');
            });
        }
        """
        self.page().runJavaScript(js)

    
    def hide_glass_overlays(self, page_indices: list[int]) -> None:
        """
        Surgically hides glass overlays for a list of unselected zero-based page indices
        so the user can read the original untranslated text immediately.

        Args:
            page_indices: List of zero-based page indices to reveal (e.g., [0, 4, 5]).
        """
        pages_json = json.dumps(page_indices)
        js = f"""
        (function() {{
            var iframe = document.getElementById('html-iframe');
            if (iframe && iframe.contentWindow) {{
                var pageIndices = {pages_json};
                pageIndices.forEach(function(idx) {{
                    var glass = iframe.contentWindow.document.getElementById('glass-overlay-t-' + idx);
                    if (glass) {{
                        glass.style.display = 'none';
                    }}
                }});
            }}
        }})();
        """
        self.page().runJavaScript(js)

    
    def reset_translation_state(self, original_texts : str) -> None:
        """
        Clears translation memories and smoothly restores the original English text 
        and scale matrices in the browser without reloading the page, preventing flashes.
        """
        # Convert python dict to a JSON string to pass it safely to JavaScript
        original_texts_json = json.dumps(original_texts)
        
        # This JS block traverses the DOM instantly, restoring the original text
        # and resetting the layout matrices to their clean English scale
        js_code = f"""
        (function() {{
            var iframe = document.getElementById('html-iframe');
            if (iframe && iframe.contentWindow) {{
                var origTexts = {original_texts_json};
                var doc = iframe.contentWindow.document;
                
                doc.querySelectorAll('span[data-trans-id]').forEach(function(span) {{
                    var transId = span.getAttribute('data-trans-id');
                    var originalText = origTexts[transId];
                    
                    if (originalText !== undefined) {{
                        // 1. Restore the original English text
                        span.innerHTML = originalText;
                        span.classList.remove('shimmer-line');
                        
                        // 2. Reset scale matrices of the parent div.t to their original dimensions
                        var divT = span.closest('div.t');
                        if (divT) {{
                            var sxOrig = parseFloat(span.getAttribute('data-sx') || '1');
                            var syOrig = parseFloat(span.getAttribute('data-sy') || '1');
                            divT.style.transform = 'matrix(' + sxOrig + ',0,0,' + syOrig + ',0,0)';
                            
                            // Remove temporary width tracking to allow fresh calculations for the next language
                            divT.removeAttribute('data-orig-sw');
                            divT.removeAttribute('data-sx-orig');
                            divT.removeAttribute('data-sy-orig');
                        }}
                    }}
                }});
            }}
        }})();
        """
        # Execute the script in-memory inside the Chromium engine
        self.page().runJavaScript(js_code)
        
    

    def set_pane_layout(self, layout_mode: str) -> None:
        """
        Adjusts split pane layout profiles.

        Args:
            layout_mode: Mode profile to apply ('both', 'pdf_only', or 'trans_only').
        """
        self.page().runJavaScript(f"setPaneLayout('{layout_mode}');")
    

    def set_zoom(self, zoom_factor: float) -> None:
        """
        Scales active document content frames.

        Args:
            zoom_factor: Percentage scale multiplier (e.g., 1.20).
        """
        self._zoom_factor = zoom_factor
        self.setZoomFactor(zoom_factor)


    def cleanup_temp_files(self) -> None:
        """ Securely deletes outdated workspace session HTML templates. """
        if self._temp_workspace_path and os.path.exists(self._temp_workspace_path):
            try:
                os.unlink(self._temp_workspace_path)
            except Exception:
                pass
            self._temp_workspace_path = None


    def closeEvent(self, event: Any) -> None:
        """
        Cleans directory files and releases browser ports before closing.

        Args:
            event: Window close event.
        """
        self.cleanup_temp_files()
        if self._temp_dir and os.path.exists(self._temp_dir):
            try:
                shutil.rmtree(self._temp_dir)
            except Exception:
                pass
        super().closeEvent(event)